### ISSUE TITLE
rare crash when setting map region

### ISSUE THREAD

**Issue by thedc89** [stkim1/MTImageMapView#4] opened 2016-04-07 17:57 UTC
I have a project in Swift where I use this lib. Sometimes when the app is loaded I swap mapped images using UISegmentedControl, this is usually when the crash happens.

<img width="700" alt="zrzut ekranu 2016-04-07 o 16 14 45" src="https://cloud.githubusercontent.com/assets/4841004/14361303/85092c2a-fcfa-11e5-9c14-aaf4d9d52011.png">

It's worth to mention that anytime I map the image, I adjust the array of points in regard to screensize(I basically made it responsive).

Here is the [link](https://github.com/thedc89/Dermoapp) to my repo with the project, run it and try swapping images with segmented control, this usually leads to crash, although not always(weird).

**Comment by stkim1** [comment] 2016-04-30 15:31
The issue comes from premature deallocation of `self.mapArea`. I've moved and fixed object allocation. Check if the issue still persists. thanks.

**Comment by thedc89** [comment] 2016-05-01 09:13
I didn't manage to reproduce the issue using the edited library, so I think we can treat it as resolved :) If I encounter anything in the future, I'll report. 
Thanks! :)

**Comment by thedc89** [comment] 2016-05-05 08:41
Unfortunately, I encountered the issue again :(

![zrzut ekranu 2016-05-05 o 10 39 52](https://cloud.githubusercontent.com/assets/4841004/15039506/f442e87e-12ad-11e6-8a33-15e1e2191bb9.png)

**Comment by stkim1** [comment] 2016-05-12 05:22
@thedc89 
I'm not quite sure how you are using it to produce the crash, but I'm sure it's somehow involved with memory management. 

The root cause might be simple or might not be. When it comes to the combination of Swift, however, I don't have any more steam to take a look into it. So I'm closing the issue.

**Closed by stkim1** 2016-05-12 05:22 UTC
